pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Deployment Name?", name: "deploymentName")
        choice(choices: ["AP-SOUTH-1", "AP-SOUTH-2", "AP-SOUTH-3"], description: "What AZ", name: "azDeploy")
        booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT?", name: "confirmDeployment")
    }

    stages{
        stage("Deploy") {
              steps {
                echo "String set to ${deploymentName} /n"
                 echo "choice set to ${azDeploy} /n"
                  echo "boolean set to ${confirmDeployment} /n"
              }
        }
    }
}