pipeline {
    agent any 

    parameters {
       string(defaultValue: "TEST", description: "EWhich environment to deploy in?", name: "deploy Env")
    }

    stages {
        stage("Demo") {
              steps {
                echo "string is set to: ${params.deployEnv}"
              }
        }
    }
}