pipeline {
    agent any 

    parameters {
       choice(choices: ["TEST", "DEV", "QA", "PRE-PROD", "PROD"], description: "EWhich environment to deploy in?", name: "deploy Env")
    }

    stages {
        stage("Demo") {
              steps {
                echo "Choice is set to: ${params.deployEnv}"
              }
        }
    }
}